name: gallery-dl-server
services:
  gallery-dl:
    build:
      context: .
      dockerfile: Dockerfile
    image: gallery-dl-server:local
    container_name: gallery-dl-server-local
    expose:
      - "9080"
    environment:
      CONTAINER_PORT: "9080"
      UID: "1000"
      GID: "1000"
      UMASK: "022"
      TZ: "UTC"
    volumes:
      - type: bind
        source: /home/jackson/.config/gallery-dl
        target: /config
      - type: bind
        source: /home/jackson/gdlserver
        target: /gallery-dl
      - type: bind
        source: /home/jackson/Downloads/gdlserver
        target: /usr/src/app/Media/gallery-dl
    labels:
      proxy.aliases: gdl.jickman.cc
    restart: unless-stopped
