name: gallery-dl-server
services:
  gallery-dl:
    image: ghcr.io/jthickma/gallery-dl-server:latest
    container_name: gallery-dl-server
    pull_policy: always
    user: "1000:1000"
    expose:
      - "9080"
    environment:
      CONTAINER_PORT: "9080"
      UMASK: "022"
      TZ: "UTC"
    volumes:
      - ./data/config:/config
      - ./data/archive:/gallery-dl
      - ./data/downloads:/usr/src/app/Media/gallery-dl
    labels:
      proxy.aliases: gdl.jickman.cc
    restart: unless-stopped
